[[plugins]]
# deinのinstallerで生成したvimrcで `Required` となっていたので追加
# 元々は以下
# "call dein#add('/home/USER/dotfiles/_vim/bundles/./repos/github.com/Shougo/dein.vim')
repo = 'Shougo/dein.vim'

[[plugins]]
repo  = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
# http://postd.cc/how-to-boost-your-vim-productivity/#gfm-7
# > 3. 範囲拡大を使う
# > vを押して、1文字を選択する
# > もう1回vを押して、選択範囲を単語に拡大する
# > さらに1回vを押して、選択範囲を段落に拡大する
# > （以下省略）
# > 範囲を拡大しすぎた場合は、<C-v>を押して前回の選択範囲に戻す
repo     = 'terryma/vim-expand-region'
hook_add = '''
    vmap v <Plug>(expand_region_expand)
    vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
# jsonのsyntax highlighting
# https://qiita.com/tomoemon/items/cc29b414a63e08cd4f89
repo = 'elzr/vim-json'

[[plugins]]
# markdownのテーブルや、インデントの開始位置を揃えてくれるやつ
# - markdownのテーブルの整形
#   :'<,'>Alignta |
# http://hamuhamu.hatenablog.jp/entry/2015/04/25/000246
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'fatih/vim-go'


[[plugins]]
# [vim-precious-の導入でtoml管理が快適に](https://qiita.com/kawaz/items/ee725f6214f91337b42b#vim-precious-%E3%81%AE%E5%B0%8E%E5%85%A5%E3%81%A7toml%E7%AE%A1%E7%90%86%E3%81%8C%E5%BF%AB%E9%81%A9%E3%81%AB)
# これの依存パッケージ
repo = 'Shougo/context_filetype.vim'

[[plugins]]
# [vim-precious-の導入でtoml管理が快適に](https://qiita.com/kawaz/items/ee725f6214f91337b42b#vim-precious-%E3%81%AE%E5%B0%8E%E5%85%A5%E3%81%A7toml%E7%AE%A1%E7%90%86%E3%81%8C%E5%BF%AB%E9%81%A9%E3%81%AB)
# > toml の hook_* オプション内にカーソルがあるときだけ、set filetype=vim させることが出来る
repo = 'osyo-manga/vim-precious'
depends = ['/context_filetype.vim']

[[plugins]]
repo = 'tomasr/molokai'

