[[plugins]]
# tree表示にするプラグイン
# :List2tree
#
# これが
# * .
#   * hoge
#   * huga
#     * piyo
#
# こうなる
# .
# ├── hoge
# └── huga
#     └── piyo
repo = 'shinespark/vim-list2tree'
on_cmd = ['List2Tree']


[[plugins]]
# toml の syntax highlighting
repo  = 'cespare/vim-toml'
on_ft = ['toml']


[[plugins]]
repo     = 'tomasr/molokai'
on_cmd   = 'colorscheme molokai'
hook_add = '''
    "highlight Normal ctermbg=none
    let g:rehash256 = 1
    let g:molokai_original = 1
'''


[[plugins]]
# Goの構造体とかを行分割したり結合したりしてくれるやつ
# gS    -> 分割
# gJ    -> 結合
repo   = 'AndrewRadev/splitjoin.vim'
on_map = ['gS', 'gJ']

