[[plugins]]
# tree表示にするプラグイン
# :List2tree
#
# これが
# * .
#   * hoge
#   * huga
#     * piyo
#
# こうなる
# .
# ├── hoge
# └── huga
#     └── piyo
repo = 'shinespark/vim-list2tree'
on_cmd = ['List2Tree']


[[plugins]]
# toml の syntax highlighting
repo  = 'cespare/vim-toml'
on_ft = ['toml']

