[[plugins]]
# tree表示にするプラグイン
# :List2tree
#
# これが
# * .
#   * hoge
#   * huga
#     * piyo
#
# こうなる
# .
# ├── hoge
# └── huga
#     └── piyo
repo = 'shinespark/vim-list2tree'
on_cmd = ['List2Tree']


[[plugins]]
# toml の syntax highlighting
repo  = 'cespare/vim-toml'
on_ft = ['toml']


[[plugins]]
# Goの構造体とかを行分割したり結合したりしてくれるやつ, struct
# gS    -> 分割
# gJ    -> 結合
repo   = 'AndrewRadev/splitjoin.vim'
on_map = ['gS', 'gJ']


[[plugins]]
# :UpdPkgSums or :UPS     -> updpkgsums
# :MkAurBall or :MAB      -> mkaurball
# :MkAurBallForce or :MAF -> mkaurball -f
repo  = 'Firef0x/PKGBUILD.vim'
on_ft = ['PKGBUILD']


[[plugins]]
# Gundo.vimによる高機能アンドゥ実装
repo             = 'sjl/gundo.vim'
on_cmd           = 'GundoToggle'
hook_post_source = '''
    nnoremap <Leader>g :GundoToggle<CR>
'''


[[plugins]]
# TaskList.vim ToDo管理
# 使ってない
repo             = 'vim-scripts/TaskList.vim'
# これ指定方法合ってるか分からん
on_map           = ['<Plug>TaskList']
hook_post_source = '''
    nmap <Leader>T <plug>TaskList
'''


[[plugins]]
# quickrunによる即時実行
repo             = 'thinca/vim-quickrun'
# これ順番逆で読み込まれ無さそう
on_map           = ['nxo', '<Plug>(quickrun)']
hook_post_source = '''
    nmap <Leader>r <Plug>(quickrun)
    let g:quickrun_config = {"*": {"runner": "vimproc"}}
'''


[[plugins]]
# Tarbarによるクラスアウトライン
repo = 'majutsushi/tagbar'
build = ['pacman -S ctags']
on_cmd = ['TagbarToggle']
hook_post_source = '''
    nmap <Leader>t :TagbarToggle<CR>
    " Exuberant ctags必須
'''

