[[plugins]]
# deinのinstallerで生成したvimrcで `Required` となっていたので追加
# 元々は以下
# "call dein#add('/home/USER/dotfiles/_vim/bundles/./repos/github.com/Shougo/dein.vim')
repo = 'Shougo/dein.vim'

[[plugins]]
repo  = 'Shougo/vimproc.vim'
build = 'make'


#--
# unite系
#--

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = ['denite.nvim']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = ['denite.nvim']

[[plugins]]
# vimfilerのために残している
repo             = 'Shougo/unite.vim'
#hook_post_source = '''
#    nnoremap [unite] <Nop>
#    nmap U [unite]
#    nnoremap <silent> [unite]b :<C-u>Unite buffer<CR>
#    nnoremap <silent> [unite]c :<C-u>Unite bookmark<CR>
#    nnoremap <silent> [unite]f :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
#    nnoremap <silent> [unite]m :<C-u>Unite file_mru<CR>
#    nnoremap <silent> [unite]o :<C-u>Unite outline<CR>
#    nnoremap <silent> [unite]r :<C-u>Unite register<CR>
#    nnoremap <silent> [unite]t :<C-u>Unite tab<CR>
#    nnoremap <silent> [unite]w :<C-u>Unite window<CR>
#
#    " start unite in insert mode
#    let g:unite_enable_start_insert = 1
#    " use vimfiler to open directory
#    call unite#custom_default_action("source/bookmark/directory", "vimfiler")
#    call unite#custom_default_action("directory", "vimfiler")
#    call unite#custom_default_action("directory_mru", "vimfiler")
#
#    " これhook側で実行させれるきがする
#    autocmd MyAutoCmd FileType unite call s:unite_settings()
#    function! s:unite_settings()
#        imap <buffer> <Esc><Esc> <Plug>(unite_exit)
#        nmap <buffer> <Esc> <Plug>(unite_exit)
#        nmap <buffer> <C-n> <Plug>(unite_select_next_line)
#        nmap <buffer> <C-p> <Plug>(unite_select_previous_line)
#    endfunction
#'''

[[plugins]]
repo             = 'Shougo/denite.nvim'
hook_add         = '''
    nnoremap [denite] <Nop>
    nmap <Leader>u [denite]
    nnoremap <silent> [denite]b :Denite buffer<CR>
    nnoremap <silent> [denite]c :Denite changes<CR>
    nnoremap <silent> [denite]f :Denite file<CR>
    nnoremap <silent> [denite]g :Denite grep<CR>
    nnoremap <silent> [denite]h :Denite help<CR>
    nnoremap <silent> [denite]l :Denite line<CR>
    nnoremap <silent> [denite]t :Denite tag<CR>
    nnoremap <silent> [denite]u :Denite menu<CR>
    nnoremap <silent> [denite]y :Denite neoyank<CR>
'''
hook_source = '''
    " 動いてない気がする
    call denite#custom#map(
        \ 'insert',
        \ '<Down>',
        \ '<denite:move_to_next_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<Up>',
        \ '<denite:move_to_previous_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<C-N>',
        \ '<denite:move_to_next_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<C-P>',
        \ '<denite:move_to_previous_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<C-J>',
        \ '<denite:move_to_next_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<C-K>',
        \ '<denite:move_to_previous_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'normal',
        \ '/',
        \ '<denite:enter_mode:insert>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<Esc>',
        \ '<denite:enter_mode:normal>',
        \ 'noremap'
        \)
'''

[[plugins]]
# ファイル操作
#
# https://twitter.com/ShougoMatsu/status/814072124742606848
# > 後継プラグインがないので正式発表はしてませんが、vimfiler の開発を続ける気はないです。
# > denite.nvimベースのファイラープラグインを作る気ではいます
repo     = 'Shougo/vimfiler'
depends  = ['unite.vim']
hook_add = '''
    nnoremap <silent><C-e> :VimFilerExplorer<CR>
    " なんか動かない
    nnoremap <Leader>e :VimFilerExplorer<CR>

    " close vimfiler automatically when there are only vimfiler open
    autocmd MyAutoCmd BufEnter * if (winnr('$') == 1 && &filetype ==# 'vimfiler') | q | endif

    let g:vimfiler_as_default_explorer = 1
    let g:vimfiler_enable_auto_cd = 1

    " .から始まるファイルおよび.pycで終わるファイルを不可視パターンに
    let g:vimfiler_ignore_pattern = "\%(^\..*\|\.pyc$\)"

    " vimfiler specific key mappings
    autocmd MyAutoCmd FileType vimfiler call s:vimfiler_settings()
    function! s:vimfiler_settings()
        " ^^ to go up
        nmap <buffer> ^^ <Plug>(vimfiler_switch_to_parent_directory)
        " use R to refresh
        nmap <buffer> R <Plug>(vimfiler_redraw_screen)
        " overwrite C-l
        nmap <buffer> <C-l> <C-w>l
    endfunction
'''

#--
# End unite系
#--


[[plugins]]
# http://postd.cc/how-to-boost-your-vim-productivity/#gfm-7
# > 3. 範囲拡大を使う
# > vを押して、1文字を選択する
# > もう1回vを押して、選択範囲を単語に拡大する
# > さらに1回vを押して、選択範囲を段落に拡大する
# > （以下省略）
# > 範囲を拡大しすぎた場合は、<C-v>を押して前回の選択範囲に戻す
repo     = 'terryma/vim-expand-region'
hook_add = '''
    vmap v <Plug>(expand_region_expand)
    vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
# jsonのsyntax highlighting
# https://qiita.com/tomoemon/items/cc29b414a63e08cd4f89
repo = 'elzr/vim-json'

[[plugins]]
# テキスト整形用プラギン
# Aligntaに乗り換え済み
repo = 'vim-scripts/Align'

[[plugins]]
# markdownのテーブルや、インデントの開始位置を揃えてくれるやつ
# - markdownのテーブルの整形
#   :'<,'>Alignta |
# http://hamuhamu.hatenablog.jp/entry/2015/04/25/000246
repo = 'h1mesuke/vim-alignta'

[[plugins]]
# 'p'によるペースト後Ctrl-p,Ctrl-nで履歴と置き換え
repo = 'vim-scripts/YankRing.vim'

[[plugins]]
# 囲まれているものに対していろいろする
# 使ってない
repo = 'tpope/vim-surround'

[[plugins]]
# [vim-precious-の導入でtoml管理が快適に](https://qiita.com/kawaz/items/ee725f6214f91337b42b#vim-precious-%E3%81%AE%E5%B0%8E%E5%85%A5%E3%81%A7toml%E7%AE%A1%E7%90%86%E3%81%8C%E5%BF%AB%E9%81%A9%E3%81%AB)
# これの依存パッケージ
repo = 'Shougo/context_filetype.vim'

[[plugins]]
# > 現在のカーソル位置のコンテキストによって filetype を切り換える為のプラグインです。 - https://github.com/osyo-manga/vim-precious
#
# [vim-precious-の導入でtoml管理が快適に](https://qiita.com/kawaz/items/ee725f6214f91337b42b#vim-precious-%E3%81%AE%E5%B0%8E%E5%85%A5%E3%81%A7toml%E7%AE%A1%E7%90%86%E3%81%8C%E5%BF%AB%E9%81%A9%E3%81%AB)
# > toml の hook_* オプション内にカーソルがあるときだけ、set filetype=vim させることが出来る
repo = 'osyo-manga/vim-precious'
depends = ['/context_filetype.vim']


[[plugins]]
# Fキーの移動を楽にするやつ
# f で検索した後に、ffff で次の文字に移動する
# ! このプラギンがtキーを使っている
repo = 'rhysd/clever-f.vim'
hook_add = '''
    " 大文字と小文字を区別しない
    let g:clever_f_ignore_case = 1

    " 大文字を入力したときのみ大文字と小文字を区別する
    let g:clever_f_smart_case = 1

    " ローマ字読みで日本語を検索する
    let g:clever_f_use_migemo = 1

    " 常にfで前に移動、Fで後ろに移動する
    let g:clever_f_fix_key_direction = 1

    " プロンプトを表示させる(fを押した時に下に `clever-f:` と表示されるやつ)
    let g:clever_f_show_prompt = 1

    " ; キーを全ての記号キーとマッチさせる
    " なんかちゃんと動いてなさそう
    let g:clever_f_chars_match_any_signs = 1
'''


[[plugins]]
# :VimShell
# iexe python
# :VimShellInteractive python
# :VimShellSendString
repo = 'Shougo/vimshell.vim'
hook_add = '''
    " http://nauthiz.hatenablog.com/entry/20101107/1289140518

    " ,is: シェルを起動
    nnoremap <silent> ,is :VimShell<CR>

    " ,ipy: pythonを非同期で起動
    nnoremap <silent> ,ipy :VimShellInteractive python<CR>

    " ,irb: irbを非同期で起動
    nnoremap <silent> ,irb :VimShellInteractive irb<CR>

    " ,ss: 非同期で開いたインタプリタに現在の行を評価させる
    vmap <silent> ,ss :VimShellSendString<CR>

    " 選択中に,ss: 非同期で開いたインタプリタに選択行を評価させる
    nnoremap <silent> ,ss <S-v>:VimShellSendString<CR>
'''


[[plugins]]
# もし colorscheme molokai が not found になる場合は以下を試すこと
# :call dein#add('tomasr/molokai')
# :call dein#recache_runtimepath()
# そもそもplugin/ ディレクトリがないのでlazy出来ない？
# :help lazy に書いてある
repo     = 'tomasr/molokai'
#on_cmd   = ['colorscheme molokai', 'molokai']
hook_add = '''
    "highlight Normal ctermbg=none
    let g:rehash256 = 1
    let g:molokai_original = 1
'''


[[plugins]]
# `:w sudo:%` でrootとして保存
# (`:w ! sudo tee %` が使えなくなったので代替手段)
# https://github.com/neovim/neovim/issues/8527
#
# ```
# " Open a current file with sudo
# :e suda:%
# " Save a current file with sudo
# :w suda:%
# " Edit /etc/sudoers
# :e suda:/etc/sudoers
# " Read /etc/sudoers (insert content under the cursor)
# :r suda:/etc/sudoers
# " Read /etc/sudoers at the end
# :$r suda:/etc/sudoers
# " Write contents to /etc/profile
# :w suda:/etc/profile
# " Save contents to /etc/profile
# :saveas suda:/etc/profile
# ```
repo     = 'lambdalisue/suda.vim'
hook_add = '''
    let g:suda#prefix = 'sudo:'
'''
# on_* を使用していないので呼ばれない気がした
hook_post_source = '''
    call suda#init('sudo:*,sudo:*/*')
'''


[[plugins]]
# インデントに色を付けて見やすくする
repo = 'nathanaelkane/vim-indent-guides'
hook_post_source = '''
    let g:indent_guides_guide_size = 1
    let g:indent_guides_enable_on_vim_startup = 1
    "IndentGuidesEnable
'''


[[plugins]]
# コメントを操作するプラギン
repo             = 'scrooloose/nerdcommenter'
hook_post_source = '''
    let NERDSpaceDelims = 1
    nmap ,, <Plug>NERDCommenterToggle
    vmap ,, <Plug>NERDCommenterToggle
    " 行の最後にコメントを追加
    nmap ,a <Plug>NERDCommenterAppend
    " カーソルの位置から行の最後までをコメントに変更
    nmap ,9 <Plug>NERDCommenterToEOL
    nmap ,s <Plug>NERDCommenterSexy
    vmap ,s <Plug>NERDCommenterSexy
    nmap ,b <Plug>NERDCommenterMinima
    vmap ,b <Plug>NERDCommenterMinima
'''


[[plugins]]
# 行末の不要な半角スペースを可視化
repo             = 'bronson/vim-trailing-whitespace'
hook_post_source = '''
    nmap d<TAB> :FixWhitespace<CR>
'''


[[plugins]]
# 別 lazy ファイルでも定義してある
#   - python_lazy
repo     = 'vim-syntastic/syntastic'


#--
# deoplete.nvim
#
# 補完
# - vimの場合は deoplete が nvim-yarp, vim-hug-neovim-rpc に依存する
# - nvim の場合は python-neovim に依存する
#   - build = 'pacman -S python-neovim'
#--


[[plugins]]
# if !nvim
repo             = 'Shougo/deoplete.nvim'
depends          = ['nvim-yarp', 'vim-hug-neovim-rpc']
hook_post_source = '''
    let g:deoplete#enable_at_startup = 1
    ":UpdateRemotePlugins
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
# Depends: pacman/python-neovim
repo = 'roxma/vim-hug-neovim-rpc'

#--
# End deoplete.nvim
#--

