[[plugins]]
# tree表示にするプラグイン
# :List2tree
#
# これが
# * .
#   * hoge
#   * huga
#     * piyo
#
# こうなる
# .
# ├── hoge
# └── huga
#     └── piyo
repo = 'shinespark/vim-list2tree'
on_cmd = ['List2Tree']


[[plugins]]
# toml の syntax highlighting
repo  = 'cespare/vim-toml'
on_ft = ['toml']


[[plugins]]
# Goの構造体とかを行分割したり結合したりしてくれるやつ, struct
# gS    -> 分割
# gJ    -> 結合
repo   = 'AndrewRadev/splitjoin.vim'
on_map = ['gS', 'gJ']


[[plugins]]
# :UpdPkgSums or :UPS     -> updpkgsums
# :MkAurBall or :MAB      -> mkaurball
# :MkAurBallForce or :MAF -> mkaurball -f
repo  = 'Firef0x/PKGBUILD.vim'
on_ft = ['PKGBUILD']

