[[plugins]]
# deinのinstallerで生成したvimrcで `Required` となっていたので追加
# 元々は以下
# "call dein#add('/home/USER/dotfiles/_vim/bundles/./repos/github.com/Shougo/dein.vim')
repo = 'Shougo/dein.vim'

[[plugins]]
repo  = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
# http://postd.cc/how-to-boost-your-vim-productivity/#gfm-7
# > 3. 範囲拡大を使う
# > vを押して、1文字を選択する
# > もう1回vを押して、選択範囲を単語に拡大する
# > さらに1回vを押して、選択範囲を段落に拡大する
# > （以下省略）
# > 範囲を拡大しすぎた場合は、<C-v>を押して前回の選択範囲に戻す
repo     = 'terryma/vim-expand-region'
hook_add = '''
    vmap v <Plug>(expand_region_expand)
    vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
# jsonのsyntax highlighting
# https://qiita.com/tomoemon/items/cc29b414a63e08cd4f89
repo = 'elzr/vim-json'

[[plugins]]
# markdownのテーブルや、インデントの開始位置を揃えてくれるやつ
# - markdownのテーブルの整形
#   :'<,'>Alignta |
# http://hamuhamu.hatenablog.jp/entry/2015/04/25/000246
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'fatih/vim-go'


[[plugins]]
# [vim-precious-の導入でtoml管理が快適に](https://qiita.com/kawaz/items/ee725f6214f91337b42b#vim-precious-%E3%81%AE%E5%B0%8E%E5%85%A5%E3%81%A7toml%E7%AE%A1%E7%90%86%E3%81%8C%E5%BF%AB%E9%81%A9%E3%81%AB)
# これの依存パッケージ
repo = 'Shougo/context_filetype.vim'

[[plugins]]
# > 現在のカーソル位置のコンテキストによって filetype を切り換える為のプラグインです。 - https://github.com/osyo-manga/vim-precious
#
# [vim-precious-の導入でtoml管理が快適に](https://qiita.com/kawaz/items/ee725f6214f91337b42b#vim-precious-%E3%81%AE%E5%B0%8E%E5%85%A5%E3%81%A7toml%E7%AE%A1%E7%90%86%E3%81%8C%E5%BF%AB%E9%81%A9%E3%81%AB)
# > toml の hook_* オプション内にカーソルがあるときだけ、set filetype=vim させることが出来る
repo = 'osyo-manga/vim-precious'
depends = ['/context_filetype.vim']

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    "colorscheme molokai
    "highlight Normal ctermbg=none
'''

[[plugins]]
# Fキーの移動を楽にするやつ
# f で検索した後に、ffff で次の文字に移動する
# ! このプラギンがtキーを使っている
repo = 'rhysd/clever-f.vim'
hook_add = '''
    " 大文字と小文字を区別しない
    let g:clever_f_ignore_case = 1

    " 大文字を入力したときのみ大文字と小文字を区別する
    let g:clever_f_smart_case = 1

    " ローマ字読みで日本語を検索する
    let g:clever_f_use_migemo = 1

    " 常にfで前に移動、Fで後ろに移動する
    let g:clever_f_fix_key_direction = 1

    " プロンプトを表示させる(fを押した時に下に `clever-f:` と表示されるやつ)
    let g:clever_f_show_prompt = 1

    " ; キーを全ての記号キーとマッチさせる
    " なんかちゃんと動いてなさそう
    let g:clever_f_chars_match_any_signs = 1
'''


[[plugins]]
# :VimShell
# iexe python
# :VimShellInteractive python
# :VimShellSendString
repo = 'Shougo/vimshell.vim'
hook_add = '''
    " http://nauthiz.hatenablog.com/entry/20101107/1289140518

    " ,is: シェルを起動
    nnoremap <silent> ,is :VimShell<CR>

    " ,ipy: pythonを非同期で起動
    nnoremap <silent> ,ipy :VimShellInteractive python<CR>

    " ,irb: irbを非同期で起動
    nnoremap <silent> ,irb :VimShellInteractive irb<CR>

    " ,ss: 非同期で開いたインタプリタに現在の行を評価させる
    vmap <silent> ,ss :VimShellSendString<CR>

    " 選択中に,ss: 非同期で開いたインタプリタに選択行を評価させる
    nnoremap <silent> ,ss <S-v>:VimShellSendString<CR>
'''
