#--
# unite/denite系
#--

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/neoyank.vim'


[[plugins]]
repo     = 'Shougo/denite.nvim'
hook_add = '''
    nnoremap [denite] <Nop>

    nmap <Leader>u  [denite]
    nmap <C-u>      [denite]

    nnoremap <silent> [denite]b     :Denite buffer<CR>
    nnoremap <silent> [denite]c     :Denite changes<CR>
    nnoremap <silent> [denite]f     :Denite file<CR>
    nnoremap <silent> [denite]g     :Denite grep<CR>
    nnoremap <silent> [denite]h     :Denite help<CR>
    nnoremap <silent> [denite]l     :Denite line<CR>
    nnoremap <silent> [denite]m     :Denite mark<CR>
    nnoremap <silent> [denite]t     :Denite tag<CR>
    nnoremap <silent> [denite]u     :Denite menu<CR>
    nnoremap <silent> [denite]y     :Denite neoyank<CR>

    nnoremap <silent> [denite]<C-b> :Denite buffer<CR>
    nnoremap <silent> [denite]<C-c> :Denite changes<CR>
    nnoremap <silent> [denite]<C-f> :Denite file<CR>
    nnoremap <silent> [denite]<C-g> :Denite grep<CR>
    nnoremap <silent> [denite]<C-h> :Denite help<CR>
    nnoremap <silent> [denite]<C-l> :Denite line<CR>
    nnoremap <silent> [denite]<C-m> :Denite mark<CR>
    nnoremap <silent> [denite]<C-t> :Denite tag<CR>
    nnoremap <silent> [denite]<C-u> :Denite menu<CR>
    nnoremap <silent> [denite]<C-y> :Denite neoyank<CR>


    " ノーマルモードで起動
    call denite#custom#option('default', {'mode': 'normal'})
    " jjでノーマルモードに切り替え
    call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')

    " INSERT mode での上下カーソル移動
    call denite#custom#map('insert', '<Down>', '<denite:move_to_next_line>', 'noremap')
    call denite#custom#map('insert', '<Up>', '<denite:move_to_previous_line>', 'noremap')
    call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
    call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')
    call denite#custom#map('insert', '<Tab>', '<denite:move_to_next_line>')
    call denite#custom#map('insert', '<S-Tab>', '<denite:move_to_previous_line>')

    " 上の階層へ移動
    call denite#custom#map('normal', '<C-u>', '<denite:move_up_path>', 'noremap')
    call denite#custom#map('insert', '<C-u>', '<denite:move_up_path>', 'noremap')

    " ウィンドウを分割して開く
    "call denite#custom#map('normal', '<C-j>', '<denite:do_action:split>', 'noremap')
    "call denite#custom#map('insert', '<C-j>', '<denite:do_action:split>', 'noremap')
    "call denite#custom#map('normal', '<C-l>', '<denite:do_action:vsplit>', 'noremap')
    "call denite#custom#map('insert', '<C-l>', '<denite:do_action:vsplit>', 'noremap')
    call denite#custom#map('insert', '<C-t>', '<denite:do_action:tabopen>')
    "call denite#custom#map('insert', '<C-v>', '<denite:do_action:vsplit>')
    call denite#custom#map('normal', 'v', '<denite:do_action:vsplit>')
    call denite#custom#map('normal', 'V', '<denite:do_action:split>')

    " / で INSERT mode に移動
    call denite#custom#map('normal', '/', '<denite:enter_mode:insert>', 'noremap')
    " <Esc> で NORMAL mode に移動
    call denite#custom#map('insert', '<Esc>', '<denite:enter_mode:normal>', 'noremap')
'''

