#--
# unite/denite系
#--

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/neoyank.vim'


[[plugins]]
repo     = 'Shougo/denite.nvim'
hook_add = '''
    nnoremap [denite] <Nop>
    nmap <Leader>u [denite]
    nnoremap <silent> [denite]b :Denite buffer<CR>
    nnoremap <silent> [denite]c :Denite changes<CR>
    nnoremap <silent> [denite]f :Denite file<CR>
    nnoremap <silent> [denite]g :Denite grep<CR>
    nnoremap <silent> [denite]h :Denite help<CR>
    nnoremap <silent> [denite]l :Denite line<CR>
    nnoremap <silent> [denite]t :Denite tag<CR>
    nnoremap <silent> [denite]u :Denite menu<CR>
    nnoremap <silent> [denite]y :Denite neoyank<CR>

    call denite#custom#option('default', {'mode': 'normal'})
    call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')

    call denite#custom#map(
        \ 'insert',
        \ '<Down>',
        \ '<denite:move_to_next_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<Up>',
        \ '<denite:move_to_previous_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<C-n>',
        \ '<denite:move_to_next_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<C-p>',
        \ '<denite:move_to_previous_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<C-j>',
        \ '<denite:move_to_next_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<C-k>',
        \ '<denite:move_to_previous_line>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'normal',
        \ '/',
        \ '<denite:enter_mode:insert>',
        \ 'noremap'
        \)
    call denite#custom#map(
        \ 'insert',
        \ '<Esc>',
        \ '<denite:enter_mode:normal>',
        \ 'noremap'
        \)
'''

