# https://qiita.com/park-jh/items/b353319efb1823c36c05

[[plugins]]
repo  = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript', 'javascriptreact']

[[plugins]]
repo  = 'othree/yajs.vim'
on_ft = ['javascript', 'typescript', 'javascriptreact']

[[plugins]]
repo  = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'typescript', 'javascriptreact']

[[plugins]]
repo     = 'othree/javascript-libraries-syntax.vim'
on_ft    = ['javascript', 'typescript', 'javascriptreact']
hook_add = '''
  let g:used_javascript_libs = 'jquery,underscore,react,flux,jasmine,d3'
  let b:javascript_lib_use_jquery = 1
  let b:javascript_lib_use_underscore = 1
  let b:javascript_lib_use_react = 1
  let b:javascript_lib_use_flux = 1
  let b:javascript_lib_use_jasmine = 1
  let b:javascript_lib_use_d3 = 1
'''

[[plugins]]
repo  = 'othree/html5.vim'
on_ft = ['javascript', 'typescript', 'javascriptreact', 'html']

[[plugins]]
repo  = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript', 'javascriptreact', 'html']

[[plugins]]
# .tern-project
repo  = 'ternjs/tern_for_vim'
on_ft = ['javascript', 'typescript', 'javascriptreact', 'html']

