[[plugins]]
# Djangoを正しくVimで読み込めるようにする
repo  = 'lambdalisue/vim-django-support'
on_ft = ['python', 'python3', 'djangohtml']


[[plugins]]
# virtualenvとdjango問題の解決
# Vimで正しくvirtualenvを処理できるようにする
repo  = 'jmcantrell/vim-virtualenv'
on_ft = ['python', 'python3', 'djangohtml']


[[plugins]]
# jedi-vim python補完・リファクタリング・リファレンス環境 ###
repo     = 'davidhalter/jedi-vim'
build    = 'pip install jedi'
#build    = 'sudo pacman -S python-jedi'
on_ft    = ['python', 'python3', 'djangohtml']
hook_add = '''
    " jediにvimの設定を任せると'completeopt+=preview'するので
    " 自動設定機能をOFFにし手動で設定を行う
    let g:jedi#auto_vim_configuration = 0
    " 補完の最初の項目が選択された状態だと使いにくいためオフにする
    let g:jedi#popup_select_first = 0
    " quickrunと被るため大文字に変更
    let g:jedi#rename_command = '<Leader>R'
    " gundoと被るため大文字に変更 (2013-06-24 10:00 追記）
    let g:jedi#goto_command = '<Leader>G'
    " docstringは表示しない
    autocmd FileType python setlocal completeopt-=preview

    " jediの補完を無効化 (deoplete-jedi が非同期で補完処理を行ってくれるため)
    let g:jedi#completions_enabled = 0
'''


# appearance.toml で定義してる
#[[plugins]]
## 補完用設定
#repo    = 'lambdalisue/vim-pyenv'
#depends = ['/jedi-vim']
#on_ft   = ['python', 'python3', 'djangohtml']


[[plugins]]
repo      = 'deoplete-plugins/deoplete-jedi'
on_source = ['jedi-vim']
hook_add  = '''
    " 説明の最大文字数。この値を超えると代わりに簡易説明が使用される
    let g:deoplete#sources#jedi#statement_length = 100

    " preview window に docstring を表示する
    let g:deoplete#sources#jedi#show_docstring = 1
'''


[[plugins]]
# python formatter
#
# flake8 と一部defaultのconfigが違うのでエラーが2重に出る
# https://github.com/python/black/blob/master/.flake8
# TODO: flake8にこの設定を入れる
#
# :Black        - フォーマット実行
repo  = 'python/black'
on_ft = ['python', 'python3', 'djangohtml']

