[[plugins]]
# Terraformのsyntax highlightとfmt
repo = 'hashivim/vim-terraform'
on_ft = ['tf']
hook_add = '''
  " terraform fmtがしんどいので使わない
  "let g:terraform_fmt_on_save=1

  " 折りたたみ関連
  " うまく動作してくれない
  "let g:terraform_fold_sections=1
  "let g:terraform_remap_spacebar=1
'''


# [[plugins]]
# # terraformだけに依存しているわけではないのでcommon.toml側で定義
# repo = 'vim-syntastic/syntastic'


[[plugins]]
# Terraformの補完
# オムニ補完を使うので C-X C-O を使う必要がある
repo = 'juliosueiras/vim-terraform-completion'
on_ft = ['tf']
# syntasticをdeinで管理するようになるまでコメントアウト
#depends = ['vim-terraform', 'syntastic']
depends = ['vim-terraform']

