[[plugins]]
# Terraformのsyntax highlightとfmt
repo     = 'hashivim/vim-terraform'
on_ft    = ['tf']
hook_source = '''
  " terraform fmtがしんどいので使わない
  "let g:terraform_fmt_on_save=1

  " 折りたたみ関連
  " うまく動作してくれない
  "let g:terraform_fold_sections=1
  "let g:terraform_remap_spacebar=1
'''


[[plugins]]
# Terraformの補完
# neovim ruby provider が必要
#   https://github.com/juliosueiras/vim-terraform-completion/issues/50
repo        = 'juliosueiras/vim-terraform-completion'
on_ft       = ['tf']
# 'w0rp/ale' ではなく syntastic が必要 (書くだけ書いてるだけ)
depends     = ['vim-terraform', 'deoplete.nvim', 'w0rp/ale']
hook_source = '''
    " deoplete config
    let g:deoplete#omni_patterns = {}

    call deoplete#custom#option('omni_patterns', {
    \ 'complete_method': 'omnifunc',
    \ 'terraform': '[^ *\t"{=$]\w*',
    \})

    call deoplete#initialize()
'''

