# beeender/Comrade とコンフリクトしたので一時的に無効化
#[[plugins]]
#repo      = 'HerringtonDarkholme/yats.vim'
#on_ft     = ['typescript']
#on_source = ['mhartington/nvim-typescript']
#
#[[plugins]]
#repo  = 'mhartington/nvim-typescript'
#on_ft = ['typescript']
#build = ['./install.sh']

