---
- name: packages | install packages | Linux
  package:
    name: "{{ packages[ansible_distribution] }}"
    state: present
    #update_cache: yes
  become: yes
  when: ansible_distribution != "MacOSX"

- name: packages | install packages | Mac
  homebrew:
    name: "{{ item }}"
    state: present
  become: no
  loop: "{{ packages[ansible_distribution] }}"
  when: ansible_distribution == "MacOSX"

