---
- name: rbenv | install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv

- name: rbenv | install rbenv-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

# 指定したversionのうち、未インストールのものをリストにする
- name: rbenv | check ruby version
  # exit code操作のためにuniqに渡している
  shell: |
    export PATH=$HOME/.gem/ruby/2.3.0/bin:$PATH
    export PATH=$HOME/.rbenv/bin:$PATH
    eval "$(rbenv init -)"
    rbenv versions --bare --skip-aliases | grep '^{{ item.version }}$' | uniq
  register: result
  changed_when: result.stdout == ''
  check_mode: no
  loop:
    "{{ rbenv }}"

- name: rbenv | install ruby by rbenv
  shell: |
    export PATH=$HOME/.gem/ruby/2.3.0/bin:$PATH
    export PATH=$HOME/.rbenv/bin:$PATH
    eval "$(rbenv init -)"
    rbenv install {{ item.item.version }}
  when: item.stdout == ''
  loop:
    "{{ result.results }}"

- name: rbenv | gem install
  gem:
    name: "{{ item.1 }}"
    executable: ~/.rbenv/shims/gem
    state: latest
  environment:
    RBENV_VERSION: "{{ item.0.version }}"
  loop:
    "{{ rbenv | subelements('packages') | list }}"

