---
- name: nodenv | install nodenv
  git:
    repo: https://github.com/nodenv/nodenv.git
    dest: ~/.nodenv

- name: nodenv | install node-build
  git:
    repo: https://github.com/nodenv/node-build.git
    dest: ~/.nodenv/plugins/node-build

- name: nodenv | install nodenv-aliases
  git:
    repo: https://github.com/nodenv/nodenv-aliases.git
    dest: ~/.nodenv/plugins/nodenv-aliases

- name: nodenv | make
  shell: cd ~/.nodenv && src/configure && make -C src
  register: result
  changed_when: "'is up to date.' not in result.stdout"

# 指定したversionのうち、未インストールのものをリストにする
- name: nodenv | check node version
  # exit code操作のためにuniqに渡している
  shell: |
    export PATH="$HOME/.nodenv/bin:$PATH"
    eval "$(nodenv init -)"
    nodenv versions --bare --skip-aliases | grep '^{{ item.version }}$' | uniq
  register: result
  changed_when: result.stdout == ''
  check_mode: no
  loop:
    "{{ nodenv }}"

- name: nodenv | install node by nodenv
  shell: |
    export PATH="$HOME/.nodenv/bin:$PATH"
    eval "$(nodenv init -)"
    nodenv install {{ item.item.version }}
  when: item.stdout == ''
  loop:
    "{{ result.results }}"

- name: nodenv | check nodenv alias version
  shell: |
    export PATH="$HOME/.nodenv/bin:$PATH"
    eval "$(nodenv init -)"
    nodenv alias --list | grep {{ item.virtualenv }} | cut -f3 -d' '
  register: result
  changed_when: (item.version != result.stdout) and result.stdout != ''
  check_mode: no
  loop:
    "{{ nodenv }}"

- name: nodenv | create aliases
  shell: |
    export PATH="$HOME/.nodenv/bin:$PATH"
    eval "$(nodenv init -)"
    nodenv alias {{ item.item.virtualenv }} {{ item.item.version }}
  when: (item.item.version != item.stdout) or item.stdout == ''
  loop:
    "{{ result.results }}"

# - nodenv local,global が設定されていない場合、executable に直接aliasのnpmを指定してもglobalのnpmを使用してしまう
# - ansible実行時のPATHの頭に /usr/bin が追加されるのでglobalの npmが優先されてしまう
#   `~/.nodenv/versions/nvim/bin/npm -g install neovim`
# - loop
#   nameに配列を渡すとコケるので1つずつ渡している
- name: nodenv | npm install
  npm:
    name: "{{ item.1 }}"
    executable: "~/.nodenv/shims/npm"
    state: latest
    global: yes
  environment:
    NODENV_VERSION: "{{ item.0.virtualenv }}"
  loop:
    "{{ nodenv | subelements('packages') | list }}"

