---
- name: tmux | install required packages
  package:
    name: "{{ item }}"
    state: present
    #update_cache: yes
  become: yes
  loop:
    # tmuxのクリップボード周り
    - xsel
  when: ansible_distribution == "ArchLinux"

- name: tmux | install tpm
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm

