---
- name: gui | libinput
  ansible.builtin.template:
    src: 30-touchpad.conf.j2
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- block:

  - name: gui | lxdm | Ensure "session=/usr/bin/qtile" is in section "[base]" in specified file
    community.general.ini_file:
      path: /etc/lxdm/lxdm.conf
      section: base
      option: session
      value: /usr/bin/cinnamon-session
      #value: /usr/bin/qtile
      no_extra_spaces: yes

  - name: gui | lxdm | Ensure "gtk_theme=" is in section "[display]" in specified file
    community.general.ini_file:
      path: /etc/lxdm/lxdm.conf
      section: display
      option: gtk_theme
      value: Adapta-Nokto-Eta
      no_extra_spaces: yes

  - name: gui | lxdm | Ensure "gtk_theme=" is in section "[display]" in specified file
    community.general.ini_file:
      path: /etc/lxdm/lxdm.conf
      section: display
      option: theme
      value: ArchlinuxFull
      no_extra_spaces: yes

  become: yes


#- block:
#
#  - name: gui | plasma | Create /usr/share/xsessions/plasma-qtile.desktop
#    ansible.builtin.template:
#      src: plasma-qtile.desktop.j2
#      dest: /usr/share/xsessions/plasma-qtile.desktop
#      owner: root
#      group: root
#      mode: '0644'
#    become: yes
#
#  tags: plasma

