---
# GUIデスクトップ

- hosts: localhost
  vars:
    packages:
      # Xorg系  / システム系
      - arandr
      - picom # compton
      - rofi # dmenu
      - xorg-xinput
      - xorg-xmodmap
      - xorg-xrandr
      - xss-lock

      # WM
      - qtile

      # Display Manager
      - lxdm
      - adapta-gtk-theme
      - papirus-icon-theme

      # Audio
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pavucontrol

      # Bluetooth
      - bluez
      - bluez-utils

      # Desktop Utils
      #- azpainter
      #- gimp
      #- mc # Midnight Commander ファイルブラウザ
      #- qtfm # ファイルマネージャー
      #- shutter
      - feh
      - geeqie
      - pcmanfm
      - vlc
      - xclip #  https://github.com/ferrine/md-img-paste.vim

      # Browser
      - chromium
      - firefox
      - firefox-i18n-ja

      # Developer Tools
      - dbeaver
      - gparted
      - remmina # VMC
      - freerdp
      - vagrant
      - virtualbox
      - wireshark-qt

      # NetworkManager
      - networkmanager
      - network-manager-applet
      - networkmanager-l2tp
      - strongswan
      - networkmanager-openconnect
      - openconnect

    aur_packages:
      # WM
      - qtile-plasma

      # Display Manager
      - lxdm-themes
      - i3lock-color #betterlockscreenが依存
      - betterlockscreen

      # Audio
      - pa-applet-git

      # Browser
      - google-chrome

      # Other
      - ttf-ricty

    services:
      - bluetooth
      - lxdm
      - networkmanager

  roles:
    - arch_base

