---
# GUIデスクトップ

- hosts: localhost
  vars:
    packages:
      # Xorg系  / システム系
      - arandr
      - picom # compton
      - rofi # dmenu
      #- termite
      - alacritty
      - ttf-ubuntu-font-family
      - xf86-input-libinput
      - xf86-video-intel
      - xorg-server
      - xorg-xinit
      - xorg-xinput
      - xorg-xmodmap
      - xorg-xrandr
      - xss-lock
      - fcitx5-mozc
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-qt
      - xclip # wslで使う
      - xorg-xbacklight
      #- iio-sensor-proxy # xps13

      # DE / WM
      ## cinnamon
      - cinnamon
      - blueberry # cinnamonで使うbluetooth manager
      - nemo
      ## qtile
      - qtile
      ## KDE
      #- plasma-meta
      #- kde-applications-meta
      #- sddm
      #- phonon-qt5-vlc #選択パッケージ (plasmaではこっちが推奨されているらしい？)
      #- cronie #選択パッケージ (デフォルトの方)

      # Display Manager
      - lxdm
      #- lightdm
      #- lightdm-webkit2-greeter # lightdm-webkit-theme-aetherが依存
      - adapta-gtk-theme
      - papirus-icon-theme

      # Audio
      - pulseaudio
      - pulseaudio-alsa
      - pulseaudio-bluetooth
      - pavucontrol
      - alsa-utils

      # xps13
      - alsa-firmware
      - alsa-ucm-conf
      - sof-firmware

      # Bluetooth
      - bluez
      - bluez-utils
      - blueman

      # Desktop Utils
      #- azpainter
      #- gimp
      #- mc # Midnight Commander ファイルブラウザ
      #- qtfm # ファイルマネージャー
      #- shutter
      - feh
      - geeqie
      - pcmanfm
      - vlc
      - xclip #  https://github.com/ferrine/md-img-paste.vim

      # Browser
      - chromium
      - firefox
      - firefox-i18n-ja

      # Developer Tools
      - dbeaver
      - gparted
      - remmina # VMC
      - freerdp
      - vagrant
      - virtualbox
      - wireshark-qt

      # NetworkManager
      - networkmanager
      - network-manager-applet
      - networkmanager-l2tp
      - strongswan
      - networkmanager-openconnect
      - openconnect

      # network
      - iwd
      - wpa_supplicant

      - acpi
      - flameshot
      #- ccat

      # other
      - exfat-utils

    aur_packages:
      # WM
      - qtile-plasma-git

      # Display Manager
      - lxdm-themes
      #- lightdm-webkit-theme-aether
      - i3lock-color #betterlockscreenが依存
      - betterlockscreen

      # Audio
      - pa-applet-git

      # Browser
      - google-chrome
      - slack-desktop

      # Developer tools
      - visual-studio-code-bin
      - google-cloud-sdk

      # Fonts
      - nerd-fonts-complete

      - zoom
      - discord

      - netdata

      - insync
      - insync-nemo

      - obs-studio

    services:
      - bluetooth.service
      - lxdm.service
      #- lightdm.service
      #- sddm.service
      #- NetworkManager.service
      - netdata.service

  roles:
    - arch_base
    - gui

