---
- hosts: localhost

  vars:

    path: ~/dotfiles

    dotfiles:
      - src: _archey3.cfg
        dest: ~/.archey3.cfg
      - src: _picom.conf
        dest: ~/.picom.conf
      - src: _gvimrc
        dest: ~/.gvimrc
      - src: _i3status.conf
        dest: ~/.i3status.conf
      - src: _ideavimrc
        dest: ~/.ideavimrc
      - src: _profile
        dest: ~/.profile
      - src: _tmux.conf
        dest: ~/.tmux.conf
      - src: _vimperatorrc
        dest: ~/.vimperatorrc
      - src: _config/nvim/init.vim
        dest: ~/.vimrc
      - src: _xinitrc
        dest: ~/.xinitrc
      - src: _XMODMAPRC
        dest: ~/.XMODMAPRC
      - src: _xmodmaprc
        dest: ~/.xmodmaprc
      - src: _xremaprc
        dest: ~/.xremaprc
      - src: _zprofile
        dest: ~/.zprofile
      - src: _zshrc.local
        dest: ~/.zshrc.local
      - src: _sommelierrc
        dest: ~/.sommelierrc
      - src: _tern-project
        dest: ~/.tern-project
      - src: _eslintrc
        dest: ~/.eslintrc
      - src: _Xresources
        dest: ~/.Xresources

      - src: _i3
        dest: ~/.i3
      - src: _vim
        dest: ~/.vim
      - src: _vimrc.d
        dest: ~/.vimrc.d
      - src: _zsh
        dest: ~/.zsh

      - src: _gtkrc-2.0
        dest: ~/.gtkrc-2.0
      - src: _config/gtk-3.0
        dest: ~/.config/gtk-3.0

      - src: _config/nvim
        dest: ~/.config/nvim
      - src: _config/qtile
        dest: ~/.config/qtile
      - src: _config/terminator
        dest: ~/.config/terminator
      - src: _config/termite
        dest: ~/.config/termite
      # TODO: mkdir
      - src: _config/oni/config.tsx
        dest: ~/.config/oni/config.tsx

    # ansible_distribution
    packages:
      Archlinux:
        - git
        - ctags
        - python-pip
        - npm
        - archey3
        - neovim
        #- neovim-python
        #- autopep8
        #- flake8
        # asdfで使う
        - unzip
      Debian:
        - git
        - neovim
        - exuberant-ctags


    # https://github.com/cimon-io/ansible-role-asdf
    asdf_plugins:
      - name: adr-tools
        versions:
          - latest
        global: latest
      - name: helm
        versions:
          - 2.14.3
          - 3.5.2
          - latest
        global: latest
      - name: istioctl
        versions:
          - latest
        global: latest
      - name: kubectl
        versions:
          - latest
        global: latest
      - name: kubeseal
        versions:
          - latest
        global: latest
      - name: kustomize
        versions:
          - latest
        global: latest
      - name: terraform
        versions:
          - latest
        global: latest
      - name: vagrant
        versions:
          - latest
        global: latest
      - name: firebase
        versions:
          - latest
        global: latest
      - name: goreleaser
        versions:
          - latest
        global: latest
      - name: etcd
        versions:
          # latestだと失敗する
          - v3.4.15
        global: v3.4.15
      - name: usacloud
        url: https://github.com/naoki912/asdf-usacloud
        versions:
          - latest
        global: latest


    pyenv:
      - version: 3.9.0
        virtualenv: neovim3
        packages:
          - pynvim
          - flake8
          - black
      - version: 2.7.18
        virtualenv: neovim2
        packages:
          - pynvim
          - flake8

    rbenv:
      - version: 2.6.3
        packages:
          - neovim
          - json # vim-terraform-completion

    nodenv:
      - version: 12.7.0
        virtualenv: nvim
        packages:
          - neovim
          - typescript
          - eslint
          - tslint
          - yarn

  roles:
    - dotfile

