---
- hosts: localhost

  vars:

    path: ~/dotfiles

    dotfiles:
      - src: _archey3.cfg
        dest: ~/.archey3.cfg
      - src: _picom.conf
        dest: ~/.picom.conf
      - src: _gvimrc
        dest: ~/.gvimrc
      - src: _i3status.conf
        dest: ~/.i3status.conf
      - src: _ideavimrc
        dest: ~/.ideavimrc
      - src: _profile
        dest: ~/.profile
      - src: _tmux.conf
        dest: ~/.tmux.conf
      - src: _vimperatorrc
        dest: ~/.vimperatorrc
      - src: _config/nvim/init.vim
        dest: ~/.vimrc
      - src: _xinitrc
        dest: ~/.xinitrc
      - src: _XMODMAPRC
        dest: ~/.XMODMAPRC
      - src: _xmodmaprc
        dest: ~/.xmodmaprc
      - src: _xremaprc
        dest: ~/.xremaprc
      - src: _zprofile
        dest: ~/.zprofile
      - src: _zshrc.local
        dest: ~/.zshrc.local
      - src: _sommelierrc
        dest: ~/.sommelierrc
      - src: _tern-project
        dest: ~/.tern-project
      - src: _eslintrc
        dest: ~/.eslintrc
      - src: _Xresources
        dest: ~/.Xresources
      - src: _alacritty.yml
        dest: ~/.alacritty.yml

      - src: _i3
        dest: ~/.i3
      - src: _vim
        dest: ~/.vim
      - src: _vimrc.d
        dest: ~/.vimrc.d
      - src: _zsh
        dest: ~/.zsh

      - src: _gtkrc-2.0
        dest: ~/.gtkrc-2.0
      - src: _config/gtk-3.0
        dest: ~/.config/gtk-3.0

      - src: _config/nvim
        dest: ~/.config/nvim
      - src: _config/qtile
        dest: ~/.config/qtile
      - src: _config/terminator
        dest: ~/.config/terminator
      # TODO: mkdir
      - src: _config/oni/config.tsx
        dest: ~/.config/oni/config.tsx

    # ansible_distribution
    packages:
      Archlinux:
        - git
        - ctags
        - python-pip
        - npm
        - archey3
        - neovim
        # asdfで使う
        - unzip
      Debian:
        - git
        - neovim
        - exuberant-ctags
      MacOSX:
        formula:
          #--
          # gnu
          #--
          - binutils
          - coreutils
          - diffutils
          - findutils
          - moreutils
          - gawk
          - gnu-sed
          - gnu-tar
          - gnutls
          - grep
          - gzip
          - screen
          - wdiff
          - wget
          - ed
          - gnu-indent
          - gnu-which
          - gnu-time
          - gnu-getopt
          - gnupg
          - tree
          #--
          # docker, kubernetes
          #--
          - docker
          - docker-compose
          - kind
          - kubebuilder
          - kubectx
          - kubernetes-cli
          - stern
          #--
          # openstack
          #--
          - openstackclient
          #--
          # command line tools
          #--
          - etcd
          - hub
          - iproute2mac
          - jq
          - neovim
          - tmux
          - tmux-xpanes
          - watch
          #--
          # language
          #--
          - go
          - python
        cask:
          #--
          # Casks
          #--
          - docker
          - iterm2
          - visual-studio-code
          - scroll-reverser
          #--
          # Casks home
          #--
          - google-chrome
          - google-drive
          - discord
          - atok
          - karabiner-elements
          - vlc


    # https://github.com/cimon-io/ansible-role-asdf
    asdf_plugins:

    pyenv:
      - version: 3.10.1
        virtualenv: neovim3
        packages:
          - pynvim
          - flake8
          - black
      #- version: 2.7.18
      #  virtualenv: neovim2
      #  packages:
      #    - pynvim
      #    - flake8

    rbenv:
      - version: 2.6.3
        packages:
          - neovim
          - json # vim-terraform-completion

    nodenv:
      - version: 18.2.0
        virtualenv: nvim
        packages:
          - neovim
          - typescript
          - eslint
          - tslint
          - yarn

  roles:
    - dotfile

