---
- hosts: localhost

  vars:

    path: ~/dotfiles

    dotfiles:
      - src: _archey3.cfg
        dest: ~/.archey3.cfg
      - src: _compton.conf
        dest: ~/.compton.conf
      - src: _gvimrc
        dest: ~/.gvimrc
      - src: _i3status.conf
        dest: ~/.i3status.conf
      - src: _ideavimrc
        dest: ~/.ideavimrc
      - src: _profile
        dest: ~/.profile
      - src: _tmux.conf
        dest: ~/.tmux.conf
      - src: _vimperatorrc
        dest: ~/.vimperatorrc
      - src: _config/nvim/init.vim
        dest: ~/.vimrc
      - src: _xinitrc
        dest: ~/.xinitrc
      - src: _XMODMAPRC
        dest: ~/.XMODMAPRC
      - src: _xmodmaprc
        dest: ~/.xmodmaprc
      - src: _xremaprc
        dest: ~/.xremaprc
      - src: _zprofile
        dest: ~/.zprofile
      - src: _zshrc.local
        dest: ~/.zshrc.local
      - src: _sommelierrc
        dest: ~/.sommelierrc

      - src: _i3
        dest: ~/.i3
      - src: _vim
        dest: ~/.vim
      - src: _vimrc.d
        dest: ~/.vimrc.d
      - src: _zsh
        dest: ~/.zsh

      - src: _gtkrc-2.0
        dest: ~/.gtkrc-2.0
      - src: _config/gtk-3.0/settings.ini
        dest: ~/.config/gtk-3.0/settings.ini

      - src: _config/nvim
        dest: ~/.config/nvim
      - src: _config/qtile
        dest: ~/.config/qtile
      - src: _config/terminator
        dest: ~/.config/terminator
      - src: _config/termite
        dest: ~/.config/termite
      # TODO: mkdir
      - src: _config/oni/config.tsx
        dest: ~/.config/oni/config.tsx

    # ansible_distribution
    packages:
      Archlinux:
        - git
        - ctags
        - python-pip
        - npm
        - archey3
        - neovim
        #- neovim-python
        #- autopep8
        #- flake8
      Debian:
        - git
        - neovim
        - exuberant-ctags


    # https://github.com/cimon-io/ansible-role-asdf
    asdf_plugins:
      - name: adr-tools
        versions:
          - 3.0.0
        global: 3.0.0
      - name: helm
        versions:
          - 2.14.3
        global: 2.14.3
      - name: istioctl
        versions:
          - 1.3.0
        global: 1.3.0
      - name: kubectl
        versions:
          - 1.13.10
          - 1.14.6
          - 1.15.3
        global: 1.15.3
      - name: kubeseal
        versions:
          - 0.8.3
        global: 0.8.3
      - name: kustomize
        versions:
          - 3.1.0
        global: 3.1.0
      - name: terraform
        versions:
          - 0.12.8
        global: 0.12.8


    pyenv:
      - version: 3.8.3
        virtualenv: neovim3
        packages:
          - pynvim
          - flake8
          - black
      - version: 2.7.16
        virtualenv: neovim2
        packages:
          - pynvim
          - flake8

    rbenv:
      - version: 2.6.3
        packages:
          - neovim
          - json # vim-terraform-completion

    nodenv:
      - version: 12.7.0
        virtualenv: nvim
        packages:
          - neovim
          - typescript
          - eslint
          - tslint


  tasks:
    - import_tasks: 01_symlink.yml
      tags:
        - 01
        - symlink

    - import_tasks: 10_packages.yml
      tags:
        - 10
        - packages

    - import_tasks: 21_pyenv.yml
      tags:
        - 21
        - pyenv

    - import_tasks: 22_rbenv.yml
      tags:
        - 22
        - rbenv

    - import_tasks: 23_nodenv.yml
      tags:
        - 23
        - nodenv

    - import_tasks: 24_goenv.yml
      tags:
        - 24
        - goenv

    - import_tasks: 30_tools.yml
      tags:
        - 30
        - tools

    - import_tasks: 31_vim.yml
      tags:
        - 31
        - vim

    - import_tasks: 32_tmux.yml
      tags:
        - 32
        - tmux

    - import_tasks: 33_zsh.yml
      tags:
        - 33
        - zsh

